# Generated by Django 5.2.3 on 2025-07-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_first_name_profile_bio_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usr',
            new_name='user',
        ),
    ]
