# Generated by Django 5.2.3 on 2025-06-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0007_notes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(blank=True, default='home/avataaars.svg', upload_to='notes-img'),
        ),
    ]
