# Generated by Django 5.2.3 on 2025-06-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0008_alter_notes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(upload_to='notes-img'),
        ),
    ]
