# Generated by Django 5.2.3 on 2025-07-02 22:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0009_alter_notes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
