# Generated by Django 5.2.3 on 2025-07-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0010_alter_notes_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(default='home/note.jpg', null=True, upload_to='notes-img'),
        ),
    ]
