# Generated by Django 5.2.3 on 2025-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0012_alter_notes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(blank=True, default='home/note.jpg', null=True, upload_to='notes-img'),
        ),
    ]
