# Generated by Django 5.2.3 on 2025-07-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0020_alter_notes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(blank=True, default='static/home/note.jpg', null=True, upload_to='notes-img'),
        ),
    ]
