# Generated by Django 5.2.3 on 2025-07-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0023_alter_notes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(blank=True, upload_to='notes-img'),
        ),
    ]
